version: '3.8'

services:
  # PostgreSQL Database - 핵심 테스트용 데이터베이스
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todomaster_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sh:/docker-entrypoint-initdb.d/01-init-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d todomaster_test"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  # Redis for caching and sessions - 캐싱 및 세션 관리
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --requirepass ""
    volumes:
      - redis-test-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres-test-data:
    driver: local
  redis-test-data:
    driver: local

# 네트워크 설정 (선택사항, 기본 bridge 네트워크 사용)
networks:
  default:
    name: todomaster-test-network